#!/usr/bin/env python3
"""Generate the surgical hand MuJoCo scene files (committed artifacts).

Offline dev tool (not a runtime node): regenerates
  mujoco/scene_objects.xml   - hand-only scene + interaction object proxies
  mujoco/panda_orca_ng.xml   - Franka Panda with the ORCA hand on the flange
  mujoco/scene_orca_ng.xml   - world wrapper for the above

Run from anywhere:  python3 generate_mujoco_scenes.py

Follows the workspace convention set by the Wuji integration
(panda_wuji_ng.xml): generated models reference meshes by ABSOLUTE source
paths, so regenerate after moving the workspace. ORCA's default classes and
materials are namespaced (class "orca", materials "orca_*") to avoid
collisions with the panda model's names.
"""

import copy
import re
import xml.etree.ElementTree as ET
from pathlib import Path

SRC = Path(__file__).resolve().parents[3]  # .../ros2_ws/src
ORCA = SRC / 'orcahand_description'
FRANKA_MJ = SRC / 'multipanda_ros2/franka_description/mujoco/franka'
OUT = Path(__file__).resolve().parents[1] / 'mujoco'

HEADER = ('GENERATED by surgical_hand_description/scripts/generate_mujoco_scenes.py'
          ' - edit the generator, not this file. Mesh paths are absolute (workspace'
          ' convention, see panda_wuji_ng.xml); regenerate after moving the workspace.')

# Untuned placeholder flange mount (mirrors the URDF-side attachment args in
# surgical_hand_franka_mujoco.launch.py - keep the two in sync).
MOUNT_POS = '0 0 0'
MOUNT_EULER = '1.5708 0 0'

# The operative unclassed defaults from orcahand_right.mjcf, namespaced.
ORCA_GEOM_DEFAULTS = {'type': 'mesh', 'friction': '1 0.005 0.001', 'condim': '3',
                      'margin': '0.0005', 'contype': '1', 'conaffinity': '1'}
ORCA_JOINT_DEFAULTS = {'type': 'hinge', 'limited': 'true', 'damping': '0.1',
                       'armature': '0.001', 'margin': '0.01', 'frictionloss': '0.001'}
ORCA_POSITION_DEFAULTS = {'ctrllimited': 'true', 'forcelimited': 'true',
                          'forcerange': '-1 1', 'kp': '2.0'}


def orca_body_tree() -> ET.Element:
    """ORCA body subtree with gravcomp on every body and materials renamed."""
    root = ET.parse(ORCA / 'v2/models/mjcf/orcahand_right_body.xml').getroot()
    body = root.find('body')  # single root body: right_tower
    for element in body.iter('body'):
        element.set('gravcomp', '1')
    for element in body.iter():
        material = element.get('material')
        if material in ('white', 'black', 'invisible'):
            element.set('material', 'orca_' + material)
    return body


def orca_assets_actuators_contacts():
    mjcf = ET.parse(ORCA / 'v2/models/mjcf/orcahand_right.mjcf').getroot()
    meshes = []
    for mesh in mjcf.find('asset'):
        mesh = copy.deepcopy(mesh)
        # Absolute path + explicit scale (the scale normally comes from the
        # unclassed mesh default, which we do not carry over).
        mesh.set('file', str(ORCA / 'v2' / mesh.get('file')))
        mesh.set('scale', '0.001 0.001 0.001')
        meshes.append(mesh)
    actuators = []
    for actuator in mjcf.find('actuator'):
        actuator = copy.deepcopy(actuator)
        actuator.set('class', 'orca')
        actuators.append(actuator)
    excludes = [copy.deepcopy(e) for e in mjcf.find('contact')]
    return meshes, actuators, excludes


def build_panda_orca():
    tree = ET.parse(FRANKA_MJ / 'panda_ng.xml')
    root = tree.getroot()
    root.set('model', 'panda orca')

    compiler = root.find('compiler')
    compiler.set('meshdir', str(FRANKA_MJ / 'assets'))
    # ORCA euler attrs assume eulerseq XYZ; panda_ng uses no euler attrs, so
    # this is safe to set globally. All ORCA eulers are single-axis anyway.
    compiler.set('eulerseq', 'XYZ')

    # Namespaced ORCA defaults.
    default_root = root.find('default')
    orca_default = ET.SubElement(default_root, 'default', {'class': 'orca'})
    ET.SubElement(orca_default, 'geom', ORCA_GEOM_DEFAULTS)
    ET.SubElement(orca_default, 'joint', ORCA_JOINT_DEFAULTS)
    ET.SubElement(orca_default, 'position', ORCA_POSITION_DEFAULTS)

    asset = root.find('asset')
    ET.SubElement(asset, 'material', {'name': 'orca_white', 'rgba': '1 1 1 1',
                                      'shininess': '0.02', 'specular': '0.005'})
    ET.SubElement(asset, 'material', {'name': 'orca_black', 'rgba': '0.1569 0.1569 0.1569 1',
                                      'shininess': '0.5', 'specular': '0.1'})
    ET.SubElement(asset, 'material', {'name': 'orca_invisible', 'rgba': '1 1 1 0',
                                      'shininess': '0', 'specular': '0'})
    meshes, actuators, excludes = orca_assets_actuators_contacts()
    asset.extend(meshes)

    # Mount the hand under panda_link8 (same attachment link the Wuji uses).
    link8 = None
    for body in root.iter('body'):
        if body.get('name') == 'panda_link8':
            link8 = body
            break
    if link8 is None:
        raise RuntimeError('panda_link8 body not found in panda_ng.xml')
    mount = ET.SubElement(link8, 'body', {'name': 'orca_mount', 'pos': MOUNT_POS,
                                          'euler': MOUNT_EULER, 'childclass': 'orca',
                                          'gravcomp': '1'})
    mount.append(orca_body_tree())

    actuator_section = root.find('actuator')
    actuator_section.extend(actuators)

    contact = root.find('contact')
    if contact is None:
        contact = ET.SubElement(root, 'contact')
    contact.extend(excludes)
    ET.SubElement(contact, 'exclude', {'body1': 'panda_link8', 'body2': 'right_tower'})

    ET.indent(tree, space='  ')
    out = OUT / 'panda_orca_ng.xml'
    text = ET.tostring(root, encoding='unicode')
    out.write_text(f'<!-- {HEADER} -->\n{text}\n')
    print(f'wrote {out}')


def build_scene_orca():
    scene = f"""<!-- {HEADER} -->
<mujoco model="panda orca scene">
  <include file="panda_orca_ng.xml"/>

  <statistic center="0.3 0 0.4" extent="1"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="120" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3" markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
  </worldbody>
</mujoco>
"""
    out = OUT / 'scene_orca_ng.xml'
    out.write_text(scene)
    print(f'wrote {out}')


def build_scene_objects():
    """Hand-only scene (upstream mount pose) + surgical interaction proxies.

    Object geoms set their type explicitly because the ORCA unclassed geom
    default is type=mesh. The suture proxy is a 4-segment ball-joint chain;
    the needle proxy a single thin capsule (a curved needle needs a mesh or
    multi-capsule weld later). Placeholder placements: within reach of the
    upright-mounted hand, not yet tuned for actual grasp demos.
    """
    orca = ORCA / 'v2'
    suture_segments = ''
    indent = '      '
    for i in range(1, 4):
        suture_segments += (f'{indent}<body name="suture_seg{i}" pos="0 0 -0.022">\n'
                            f'{indent}  <joint name="suture_ball{i}" type="ball" damping="0.001"/>\n'
                            f'{indent}  <geom name="suture_geom{i}" type="capsule" size="0.0005 0.01" mass="0.0005" rgba="0.2 0.3 0.8 1"/>\n')
    suture_close = ''.join(f'{indent}</body>\n' for _ in range(1, 4))

    scene = f"""<!-- {HEADER} -->
<mujoco model="surgical hand objects scene">
  <compiler angle="radian" eulerseq="XYZ" meshdir="{orca}"/>

  <include file="{orca}/models/assets/scene.xml"/>
  <include file="{orca}/models/assets/options.xml"/>
  <include file="{orca}/models/mjcf/orcahand_right.mjcf"/>

  <worldbody>
    <!-- Hand mounted upright, same pose as upstream scene_right.xml -->
    <body name="right_mount" pos="0.09363 0.00332 0.058" euler="1.5708 0 0">
      <include file="{orca}/models/mjcf/orcahand_right_body.xml"/>
    </body>

    <!-- Needle-driver handle proxy: free cylinder, ~30 g -->
    <body name="tool_handle" pos="0.25 0.0 0.03">
      <freejoint name="tool_handle_free"/>
      <geom name="tool_handle_geom" type="cylinder" size="0.006 0.06" mass="0.03" rgba="0.6 0.6 0.65 1"/>
    </body>

    <!-- Phantom tissue block: fixed, slightly soft contact -->
    <body name="phantom_block" pos="0.25 0.15 0.02">
      <geom name="phantom_block_geom" type="box" size="0.06 0.04 0.02" mass="0.2" rgba="0.9 0.75 0.7 1" solref="0.01 0.5"/>
    </body>

    <!-- Needle proxy: straight thin capsule, 1 g (curved mesh later) -->
    <body name="needle_proxy" pos="0.25 -0.12 0.01">
      <freejoint name="needle_proxy_free"/>
      <geom name="needle_proxy_geom" type="capsule" size="0.0006 0.006" mass="0.001" rgba="0.85 0.85 0.9 1"/>
    </body>

    <!-- Suture proxy: 4-segment ball-joint capsule chain -->
    <body name="suture_root" pos="0.30 -0.12 0.08">
      <freejoint name="suture_free"/>
      <geom name="suture_geom0" type="capsule" size="0.0005 0.01" mass="0.0005" rgba="0.2 0.3 0.8 1"/>
{suture_segments}{suture_close}    </body>
  </worldbody>
</mujoco>
"""
    out = OUT / 'scene_objects.xml'
    out.write_text(scene)
    print(f'wrote {out}')


if __name__ == '__main__':
    OUT.mkdir(parents=True, exist_ok=True)
    build_scene_objects()
    build_panda_orca()
    build_scene_orca()
